Use 6.11 package registry
The `KDECI_PACKAGE_PROJECT` is used in scripts/icon_extractor.py,
and pointing to a registry that no longer exists causes the following error:

```
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
```